name: Tree-sitter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_grammar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up tree-sitter CLI
        uses: tree-sitter/setup-action/cli@v1
        with:
          install-lib: false

      - name: Run Tree-sitter Tests
        run: tree-sitter test
